### ISSUE TITLE
Gem turbolinks support

### ISSUE THREAD

**Issue by framis** [apneadiving/Google-Maps-for-Rails#320]
The map does not show when the gem Turbolinks is installed.

http://stackoverflow.com/questions/13807686/gmaps4rails-and-turbolinks-not-loading-without-full-page-refresh

**Comment by bishisht** [comment]
I did just what you said @fiedl  but I am getting an error

`Sprockets::FileNotFound at /
couldn't find file 'gmaps/google' with type 'application/javascript'`

**Comment by fiedl** [comment]
@bishisht : I've recently reviewed the issue, because it felt wrong to still live with the fork rather than to use the upstream gem.

It surely depends on your use case, but for our limited use it looks like dropping the gem and going with the native gmaps api is worth considering.

Our first experiments suggest there's absolutely no issue with turbolinks when using the gmaps api directly. 

If you're interested I'll reference the commit here when pushing it to github.
