### ISSUE TITLE
Retrieving OVER_QUERY_LIMIT status from a model?

### ISSUE THREAD

**Issue by straydogstudio** [apneadiving/Google-Maps-for-Rails#341]
Is there some way to know (outside of the log) if you're getting an 'OVER_QUERY_LIMIT' from Google with an acts_as_gmappable model? If I call `Gmaps4rails.geocode(address)` it raises an exception with the status. I see the status is recorded in the log for the model, but the exception itself is not used to store the error message. 

Thanks for the gem

**Comment by LucasCioffi** [comment]
@apneadiving and @mattholtom based on the conversation thread at https://github.com/TGRHavoc/live_map-interface/issues/17 about Google restricting use that is missing an API key, does that mean we cannot use v1.X of gmaps4rails, because we'll be over the quota limit?  Or is there a way to add an API key to v1.X?

I'm seeing this bug in production:
<img width="774" alt="screen shot 2018-10-12 at 12 37 26 am" src="https://user-images.githubusercontent.com/1825103/46848361-57c46c80-cdb7-11e8-8b8b-b52a0280a945.png">

Any help is greatly appreciated!
